### ISSUE TITLE
Unable to import projects

### ISSUE THREAD

**Issue by Twea-zz-kly** [AppyBuilder/AppyBuilderPersonal#1]
I created a project using the online version of AppyBuilder however when attempting to import the .aia file into AppyBuilderPersonal it opens a browser alert popup saying "This project was saved with a newer version of the AppyBuilder system. We will attempt to load the project, but there may be compatibility issues." and when I click OK it just repeats this popup forever until I close the localhost window.

Is there a newer version available to download? Otherwise how could I fix this?

**Comment by PeterMathijssen** [comment]
Do you use any components not available in the offline version?

**Comment by Twea-zz-kly** [comment]
I'm not sure - what kinds of components could cause this issue? I thought the offline version was kept in sync with the online one. I don't use any extensions, just default components.

**Comment by PeterMathijssen** [comment]
The online version is at the moment not in sync with the offline version.

**Comment by Twea-zz-kly** [comment]
Ok thanks
